server:
  port: 8080    # 기본 포트 설정
  servlet:
    context-path: /

spring:
  # H2 데이터 베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # jpa 제공 하는 ddl-auto 옵션 : 엔티티만 등록해 놓으면 DDL을 자동으로 작성하여 테이블을 생성하거나 수정해주는 설정
  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시 기존 테이블 삭제 후 테이블을 새로 생성
    show-sql: true  # console 창에 sql 출력
    properties:
      hibernate:
        format_sql: true    # console 창에 sql 예쁘게 출력
        default_batch_fetch_size: 500   # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false   # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기 합을 100MB 제한

logging:
  level:
    org.hibernate.type: trace  # console 창에 조건에 바인딩 되는 값 및 조회 결과 , log level : TRACE > DEBUG > INFO > WARN > ERROR > FATAL
    com.app: debug             # openfeign 로그를 보기 위해 프로젝트 루트 패키지 기준 로그 레벨을 DEBUG로 설정 (운영 환경에서는 info)

feign:
  client:
    config:
      default:
        connectTimout: 5000
        readTimeout: 5000
    

